class KitchenRunner{
	public static void main(String[] args)
	{
		String cookWare="Glass cook top";
		System.out.println(cookWare);
		
		
		String knife="used to chop";
		System.out.println(knife);
		String scissors="used to cut things";
		System.out.println(scissors);
		String spoonSmall="to dissolve the sweetners in the beverages accordingly";
		System.out.println(spoonSmall);
		String spoonMedium="usually a tablespoon with a shallow, oval-shaped design";
		System.out.println(spoonMedium);
		String soupSpoon="with a large or rounded bowl for eating soup";
		System.out.println(soupSpoon);
		String spatula="A spatula is a hand-held tool that is used for lifting, flipping, or spreading";
		System.out.println(spatula);
		String ladle="with a deep bowl and a long handle attached at a steep angle";
		System.out.println(ladle);
		String peeler="The peeler is faster and safer than using a knife to peel fruits and vegetables";
		System.out.println(peeler);
		String grater="A grater, also known as a shredder, is a kitchen utensil used to grate foods into fine pieces";
		System.out.println(grater);
		String blender="used to mix, crush, purée or emulsify food and other substances";
		System.out.println(blender);
		String masher="A potato masher is a kitchen tool that is used to mash cooked potatoes";
		System.out.println(masher);
		String rollingPin="A rolling pin is a cylindrical food preparation utensil used to shape and flatten dough";
		System.out.println(rollingPin);
		String cuttingBoard="A cutting board is a durable board on which to place material for cutting";
		System.out.println(cuttingBoard);
		String whisk="A whisk is a cooking utensil which can be used to blend ingredients smooth or to incorporate air into a mixture";
		System.out.println(whisk);
		String measuringCup="Measuring cups are used for precisely measuring the volume of liquid or solid cooking ingredients";
		System.out.println(measuringCup);
		String colander="For draining pasta or washing vegetables and salad greens";
		System.out.println(colander);
		String apron="A kitchen apron is a cloth used by chefs and other cooks to protect their clothing and prevent food and debrisfrom contaminating their clothes";
		System.out.println(apron);
		String foodProcessor="It may be a bit bulky to haul off the pantry shelf, but a food processor takes the elbow grease out of innumerable kitchen tasks";
		System.out.println(foodProcessor);
		String grillPan="If you don’t have outdoor space or it’s too cold to fire up the grill";
		System.out.println(grillPan);
		String rice="Used in stir-fries, pilafs, sushi, and rice puddings";
		System.out.println(rice);
		String oats="Used in oatmeal, granola, and baking";
		System.out.println(oats);
		String barley="Used in soups, stews, and salads";
		System.out.println(barley);
		String millet="Used in porridge, salads, and as a rice substitute";
		System.out.println(millet);
		String lentils="Used in soups, stews, and salads";
		System.out.println(lentils);
		String kidneyBeans="Used in chili, stews, and salads";
		System.out.println(kidneyBeans);
		String peas="Used in a pea and mint soup for a refreshing starter";
		System.out.println(peas);
		String spinach="Used in a green smoothie for a nutrient boost";
		System.out.println(spinach);
		String kale=" Used to make crispy kale chips as a healthy snack";
		System.out.println(kale);
		String broccoli="Used in a broccoli and cheddar soup for a creamy meal";
		System.out.println(broccoli);
		String cauliflower="Used to create cauliflower rice as a low-carb side";
		System.out.println(cauliflower);
		String carrots="Used in a sweet carrot and ginger juice";
		System.out.println(carrots);
		String bellPeppers="Used in a colorful bell pepper stir-fry";
		System.out.println(bellPeppers);
		String zucchini="Used to make zucchini noodles (zoodles) as a pasta substitute";
		System.out.println(zucchini);
		String eggPlant="Used in a traditional eggplant parmesan";
		System.out.println(eggPlant);
		String tomatoes="Used to make a fresh tomato bruschetta topping";
		System.out.println(tomatoes);
		String cucumbers="Used in a cooling cucumber and yogurt raita";
		System.out.println(cucumbers);
		String mushrooms="Used to create a savory mushroom risotto";
		System.out.println(mushrooms);
		String almonds="good for memory";
		System.out.println(almonds);
		String ac="Find beauty everywhere.";
		System.out.println(ac);
		String earphone="Radiate positivity.";
		System.out.println(earphone);
		String window="Spread kindness.";
		System.out.println(window);
		String bulb="Value relationships.";
		System.out.println(bulb);	
		String watch="Be present.";
		System.out.println(watch);
		String band="Laugh often.";
		System.out.println(band);
		String finger="Stay curious.";
		System.out.println(finger);
		String hair="Savor simplicity.";
		System.out.println(hair);
		String bed="Practice gratitude.";
		System.out.println(bed);
		String plate="Discover inner peace.";
		System.out.println(plate);
		String city="Inspire others.";
		System.out.println(city);		
		String ring="Count your blessings.";
		System.out.println(ring);
		String girl="Trust your journey.";
		System.out.println(girl);
		String boy="Create happiness.";
		System.out.println(boy);
		String bottle="Listen more.";
		System.out.println(bottle);
		String pant="Speak kindly.";
		System.out.println(pant);
		String clip="Celebrate life.";
		System.out.println(clip);
		String teddy="Enjoy the moment.";
		System.out.println(teddy);
		String top="Keep moving forward.";
		System.out.println(top);
		String mirror="Never give up.";
		System.out.println(mirror);
		String animal="Breathe deeply.";
		System.out.println(animal);
		String towel="Live authentically.";
		System.out.println(towel);
		String handel="Be courageous.";
		System.out.println(handel);
		String box="Grow through challenges.";
		System.out.println(box);
		String chain="Be the light.";
		System.out.println(chain);
		String wire="Stay humble.";
		System.out.println(wire);
		String krutha="Follow your heart.";
		System.out.println(krutha);
		String blanket="to keep sleeping person warm";
		System.out.println(blanket);
		String cold="winter season";
		System.out.println(cold);
		String summer="sun is hot";
		System.out.println(summer);
		String water="for health good";
		System.out.println(water);
		String black="fav colour";
		System.out.println(black);
		String bike="riding";
		System.out.println(bike);
		String tab="for working";
		System.out.println(tab);
		String whatsapp="chatting";
		System.out.println( whatsapp);
		String insta="scrolling";
		System.out.println(insta);
		String tiger="cruel";
		System.out.println(tiger);
		String cow=" god";
		System.out.println(cow);
		String jamoon="very tasty";
		System.out.println(jamoon);
		



    
	}
	
}
